spring.application.name=ProductosJSS
server.port=8081

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/basejoyas?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Santiago
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT (necesario para JwtUtils)
app.jwt.secret=TuSuperClaveSecretaLarga_Y_Muy_Aleatoria_Para_Firmar_JWT_1234567890
# Ejecuta la migración SOLO cuando esté en true
app.migrate.passwords=true

# Monitoreo - Actuator y Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
