global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'productosjss-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['productosjss:8081']

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
