apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  database-root-password: "rootpassword123"
  jwt-secret: "TuSuperClaveSecretaLarga_Y_Muy_Aleatoria_Para_Firmar_JWT_1234567890"
